(require 'color-theme)
(require 'color-theme-molokai)


;; {{ work around color theme bug
;; @see https://plus.google.com/106672400078851000780/posts/KhTgscKE8PM
(defadvice load-theme (before disable-themes-first activate)
  ;; diable all themes
  (dolist (i custom-enabled-themes)
    (disable-theme i)))
;; }}

(color-theme-molokai)

;; This line must be after color-theme-molokai! Don't know why.
(setq color-theme-illegal-faces "^\\(w3-\\|dropdown-\\|info-\\|linum\\|yas-\\|font-lock\\)")

;;baoxl light theme
(eval-when-compile    (require 'color-theme))
(defun baoxl-light-theme ()
  "Color theme by baoxl, created 2018-12-31."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "white")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "black")
      (mouse-color . "black"))
     ((browse-kill-ring-current-entry-face . highlight)
      (browse-kill-ring-inserted-item-face . highlight)
      (browse-kill-ring-separator-face . bold)
      (buffer-face-mode-face . variable-pitch)
      (compilation-message-face . underline)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . link)
      (goto-address-url-mouse-face . highlight)
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "Ubuntu Mono"))))
     (artbollocks-face ((t (:background "White" :foreground "Purple"))))
     (artbollocks-lexical-illusions-face ((t (:background "magenta" :foreground "black"))))
     (artbollocks-passive-voice-face ((t (:background "White" :foreground "Gray"))))
     (artbollocks-weasel-words-face ((t (:background "White" :foreground "Brown"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "RoyalBlue3"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "medium blue"))))
     (company-echo ((t (nil))))
     (company-echo-common ((t (:background "firebrick4"))))
     (company-preview ((t (:background "light blue" :foreground "black"))))
     (company-preview-common ((t (:background "light blue" :foreground "black"))))
     (company-preview-search ((t (:foreground "darkred" :background "light blue"))))
     (company-scrollbar-bg ((t (:foreground "black" :background "wheat"))))
     (company-scrollbar-fg ((t (:background "darkred"))))
     (company-template-field ((t (:background "orange" :foreground "black"))))
     (company-tooltip ((t (:background "cornsilk" :foreground "black"))))
     (company-tooltip-annotation ((t (:background "cornsilk" :foreground "firebrick4"))))
     (company-tooltip-common ((t (:background "cornsilk" :foreground "darkred"))))
     (company-tooltip-common-selection ((t (:background "light blue" :foreground "darkred"))))
     (company-tooltip-mouse ((t (:background "darkseagreen2"))))
     (company-tooltip-search ((t (:background "light blue" :foreground "black"))))
     (company-tooltip-selection ((t (:foreground "black" :background "light blue"))))
     (compilation-column-number ((t (:foreground "VioletRed4"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red1"))))
     (compilation-info ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (compilation-line-number ((t (:foreground "Purple"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 128))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "black"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (error ((t (:bold t :foreground "Red1" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (ffap ((t (:background "darkseagreen2"))))
     (fic-author-face ((t (:background "white" :foreground "orangered" :underline t))))
     (fic-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flx-highlight-face ((t (:bold t :foreground "sienna" :underline t :weight bold))))
     (flymake-errline ((t (:background "LightPink"))))
     (flymake-infoline ((t (:background "LightGreen"))))
     (flymake-warnline ((t (:background "LightBlue2"))))
     (flyspell-duplicate ((t (:bold t :weight bold :foreground "DarkOrange" :underline t))))
     (flyspell-incorrect ((t (:bold t :weight bold :foreground "Red1" :underline t))))
     (fringe ((t (:background "grey95"))))
     (git-gutter:added ((t (:bold t :foreground "green" :weight bold))))
     (git-gutter:deleted ((t (:bold t :foreground "red" :weight bold))))
     (git-gutter:modified ((t (:bold t :foreground "magenta" :weight bold))))
     (git-gutter:separator ((t (:bold t :foreground "cyan" :weight bold))))
     (git-gutter:unchanged ((t (:background "yellow"))))
     (glyphless-char ((t (:height 0.6))))
     (guide-key/highlight-command-face ((t (:foreground "orange red"))))
     (guide-key/key-face ((t (:foreground "dark green"))))
     (guide-key/prefix-command-face ((t (:foreground "blue"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkseagreen2"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Red1" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "dark slate blue"))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "RoyalBlue3" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (nil))))
     (next-error ((t (:foreground "gtk_selection_fg_color" :background "gtk_selection_bg_color"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (page-break-lines ((t (:foreground "Firebrick" :slant normal :weight normal))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (rainbow-delimiters-depth-1-face ((t (:foreground "#707183"))))
     (rainbow-delimiters-depth-2-face ((t (:foreground "#7388d6"))))
     (rainbow-delimiters-depth-3-face ((t (:foreground "#909183"))))
     (rainbow-delimiters-depth-4-face ((t (:foreground "#709870"))))
     (rainbow-delimiters-depth-5-face ((t (:foreground "#907373"))))
     (rainbow-delimiters-depth-6-face ((t (:foreground "#6276ba"))))
     (rainbow-delimiters-depth-7-face ((t (:foreground "#858580"))))
     (rainbow-delimiters-depth-8-face ((t (:foreground "#80a880"))))
     (rainbow-delimiters-depth-9-face ((t (:foreground "#887070"))))
     (rainbow-delimiters-mismatched-face ((t (:foreground "#88090B"))))
     (rainbow-delimiters-unmatched-face ((t (:foreground "#88090B"))))
     (region ((t (:background "gtk_selection_bg_color" :foreground "gtk_selection_fg_color"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow1"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (success ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-func ((t (:foreground "Blue1"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (window-numbering-face ((t (:bold t :foreground "DeepPink" :underline "DeepPink" :weight bold)))))))
(add-to-list 'color-themes '(baoxl-light-theme  "THEME NAME" "YOUR NAME"))
(baoxl-light-theme)
;; (color-theme-select 'color-theme-xp)
;; (color-theme-xp)

(provide 'init-color-theme)
